### ISSUE TITLE
Utiliser smartenergy meter avec la nouvelle section Energy. 

### ISSUE THREAD

**Issue by kayrozen** [francispoisson/hilo#29]
La dernière version de Home Assistant a maintenant une section Énergie et malheureusement, smart energy meter n'y apparait pas. Selon HA, il faut spécifier quelques metadata au sensor pour quil soit recconu par la nouvelle fonction. 

https://www.home-assistant.io/docs/energy/electricity-grid/

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by vgibara** [comment]
Francis a déjà répondu à ça ici: https://github.com/francispoisson/hilo/issues/24#issuecomment-903278608

Et voici mon setup, pour calculer le coût quotidien. C'est peut-être pas parfait, mais ça marchait jusqu'à ce que le bug d'avant-hier survienne avec Hilo. 

J'ai créé quelques input pour entrer manuellement, lorsqu'ils changent, les coûts d'électricité:
input_number.electricity_first40      0.06159
input_number.electricity_restofday     0.09502
input_number.electricity_access_fee     0.41168
input_number.electricity_current_price     (celui-ci est automatique et sert pour l'automation ** je ne suis plus certain si cette partie des automations est encore utilisée dans mon setup....)

Ensuite, le utility_meter daily_energy va créer 2 sensors:
sensor.daily_energy_first40
sensor.daily_energy_restofday

J'ai fait 2 automations qui vont modifier dans quel sensor les données sont comptées. Donc, premiers 40 kWh dans daily_energy_first40, et ensuite dans daily_energy_restofday. Voir plus bas pour les 2 automations.


utility_meter:
  daily_energy:
    source: sensor.energy_spent
    name: Électricité quotidienne
    cycle: daily
    tariffs:
      - first40
      - restofday

  - platform: template
    sensors:
      daily_energy_cost:
        entity_id:
          - sensor.energy_spent
        value_template: >-
          {{ '%.2f' | format(((states('sensor.daily_energy_first40') | float * states('input_number.electricity_first40') | float) + (states('sensor.daily_energy_restofday') | float * states('input_number.electricity_restofday') | float) + states('input_number.electricity_access_fee') | float) | round(2)) }}

  - platform: integration
    source: sensor.smartenergymeter
    name: energy_spent
    unit_prefix: k
    method: left
    round: 2




alias: Tarification d'électricité - First 40
description: ''
trigger:
  - platform: state
    entity_id: sensor.daily_energy_first40
    to: '40'
condition: []
action:
  - service: utility_meter.select_tariff
    target:
      entity_id: utility_meter.daily_energy
    data:
      tariff: restofday
  - service: input_number.set_value
    target:
      entity_id: input_number.electricity_current_price
    data:
      value: '{{ states(''input_number.electricity_restofday'') | float }}'
mode: single



alias: Tarification d'électricité - Reset Daily
description: ''
trigger:
  - platform: time
    at: '00:00'
condition: []
action:
  - service: utility_meter.select_tariff
    target:
      entity_id: utility_meter.daily_energy
    data:
      tariff: first40
  - service: input_number.set_value
    target:
      entity_id: input_number.electricity_current_price
    data:
      value: '{{ states(''input_number.electricity_first40'') | float }}'
mode: single

**Comment by kayrozen** [comment]
Nice ! Merci :)

**Comment by isbkch** [comment]
Mon problème est cette erreur quand je veux configurer le cout dans le dashboard Energy (ta variable `electricity_current_price` s'appelle `energy_current_cost` dans mon exemple
![Screen Shot 2021-10-19 at 11 33 51 AM](https://user-images.githubusercontent.com/216867/137944195-bccc9bef-e9f9-4423-af72-b8f583de4005.png)


Voici comment je set le cout d'énergie
![Screen Shot 2021-10-19 at 11 33 43 AM](https://user-images.githubusercontent.com/216867/137944250-733a83ca-7cfd-4c35-89b4-a26a44f0f35d.png)


J'ai utilisé tes deux automations aussi, voici la premiere

```
alias: Energy Cost - First 40
description: ''
trigger:
  - platform: state
    entity_id: input_number.energy_cost_first_40
    to: '40'
condition: []
action:
  - service: utility_meter.select_tariff
    target:
      entity_id: utility_meter.daily_energy
    data:
      tariff: after_40
  - service: input_number.set_value
    target:
      entity_id: input_number.energy_current_cost
    data:
      value: '{{ states(''input_number.energy_cost_after_40'') | float }}'
mode: single
```

Et la deuxieme:
```
alias: Energy Cost - Reset Daily
description: ''
trigger:
  - platform: time
    at: '00:00:00'
condition: []
action:
  - service: utility_meter.select_tariff
    target:
      entity_id: utility_meter.daily_energy
    data:
      tariff: first_40
  - service: input_number.set_value
    target:
      entity_id: input_number.energy_current_cost
    data:
      value: '{{ states(''input_number.energy_current_cost'') | float }}'
mode: single
```

Et ça c'est mes configurations:
```
utility_meter:
  daily_energy:
    source: sensor.total_energy_consumed
    name: Daily Energy
    cycle: daily
    tariffs:
      - first_40
      - after_40

- platform: template
  sensors:
    daily_energy_cost:
      entity_id:
        - sensor.energy_spent
      value_template: "{{ '%.2f' | format(((states('sensor.daily_energy_first_40') | float * states('input_number.energy_cost_first_40') | float) + (states('sensor.daily_energy_after_40') | float * states('input_number.energy_cost_after_40') | float) + states('input_number.energy_access_fee') | float) | round(2)) }}"
```
